### ISSUE TITLE
Bot gold sending messages to GC bug!!

### ISSUE THREAD

**Issue by Choppaaz** [Icecrown-Community/ICC-Member-Website-Public#38] opened 2021-01-20 16:59 UTC
So I got one of the messages from the bot with 0 gold instead of 400k, here are the pictures: 

![image](https://user-images.githubusercontent.com/77581204/105208237-82d2c480-5b59-11eb-90f9-dcdd287f7d99.png)

![image](https://user-images.githubusercontent.com/77581204/105208273-91b97700-5b59-11eb-8b4a-ffd85df74c66.png)

**Comment by Bgabor997** [comment] 2021-01-22 10:56
i tried it on local, couldn't reproduce this bug, the only case when this happened for me, when the customer's deposit is 0

**Comment by iElsha** [comment] 2021-01-25 11:42
Fixed with  #57

**Closed by iElsha** 2021-01-25 11:42 UTC
Labels: bug
