### ISSUE TITLE
Customer booking order bug

### ISSUE THREAD

**Issue by Choppaaz** [Icecrown-Community/ICC-Member-Website-Public#28] opened 2021-01-18 23:01 UTC
We got a bug that show some customers who were booked late at the start of the customer list, this caused me to pass some as I couldn't notice them up... 

Issue here: 
![image](https://user-images.githubusercontent.com/77581204/104969616-0bd2ea00-59fa-11eb-8061-5d6424f2be02.png)

while some going down in the right place: 
![image](https://user-images.githubusercontent.com/77581204/104969656-273df500-59fa-11eb-9440-619543cb2cfc.png)

**Comment by iElsha** [comment] 2021-01-19 11:01
@Choppaaz this is normal even if it's a bug as we haven't implemented raids over two days but only on one

**Comment by iElsha** [comment] 2021-01-19 11:06
This won't be fixed for now except if you feel it needs to be changed if it creates a lot of confusion/errors

**Comment by Choppaaz** [comment] 2021-01-19 21:33
As I said above, we almost passed some customers cause as GC we go by the sequence and once we are down sometimes new customers (with late times) shows up and we won't notice it.

**Comment by Bgabor997** [comment] 2021-01-19 21:49
Its kinda urgent i think, the 20:00 ST curve runs messed up bcs of this
![image](https://user-images.githubusercontent.com/25648979/105097134-63c82a00-5aa8-11eb-807a-e92b2822693d.png)
but i don't rlly know why its messed up
Maybe we should only get the hours and minutes from the time picker and create a date object for the day of the raid with the picked time?

**Comment by iElsha** [comment] 2021-01-20 08:15
**How time shift are handled?**

By default when creating a new booking, you need to select a time. This is not just a "time" in our side, this is a date (already defined) where you select the time. The date is always the same date as the raid.

---

**What's the bug?**
As the date is always the same, if you want to create a shift on the next day (00:30 for instance), this is going to be created as a shift on the day of the raid at 00:30.

---

**How to fix it**
Two solutions:
1. Use a date **and** time select instead of just the time
 ![image](https://user-images.githubusercontent.com/38140638/105145414-fe535800-5afe-11eb-86f7-de1da370cd04.png)
The issue is that we'll ask for a date input that is often useless (even if well defined)
2. Change the sorting algorithm to sort depending on the start of the raid that would be the origin point
Exemple: raid start at 20:00. Start point is 20:00 -> meaning that we deduct 20h to the date and it's a start at 00:00. We'll do the same on other dates the raid starting at 21:00 will see the calculation : `21 - 20 % 24` and for a raid starting at 1:00 (in fact the other day but not really on the code) `1 - 20 % 24 = -19  % 24 = 5`. The order will then be good without needed any extra input from the user.

As storing the date is not that important on an analysis side, I would prefer the second suggestion as it stays transparent for the user.

**Comment by Bgabor997** [comment] 2021-01-20 09:12
i vote on the 2. solution, because it can be confusing or hard for advertisers to pick date and time, so if we change the sorting algorithm it will be the same for them but we fix the problem

**Comment by Shienx** [comment] 2021-01-20 09:41
Im also vor the 2. solution, it would be cleaner and there wouldnt be a need of more action taken on the side of the advertisers.

**Comment by Suzaru** [comment] 2021-01-20 09:44
Solution 2 sounds more error proof. Less user input, less margin of error. Never underestimate the Layer8 issue 😅.

**Comment by ICCDesi** [comment] 2021-01-20 10:00
You can also add a colour flame around a customer together with a tick-box so its confirmed that this person has been invited and/or done. I'm sorry but i like such things. Apart  from that, 2.

**Comment by Bgabor997** [comment] 2021-01-20 10:08
@ICCDesi thats done with the gc improvements

**Comment by Choppaaz** [comment] 2021-01-20 13:37
I vote for solution 2

**Comment by iElsha** [comment] 2021-01-20 14:02
Solution 2 will be implemented by tonight. This will be fixed for this evening curve.

**Closed** 2021-01-20 18:07 UTC
Labels: Urgent, bug
