### ISSUE TITLE
Sort by server - gc option

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#79] opened 2021-02-03 07:59 UTC
My idea is, to be able to sort the customers by server. This would help the mail sending proccess, especially on curves

**Comment by Dejnaa** [comment] 2021-02-04 13:40
Choppa already posted this suggestion :)

**Comment by Wanhedaa** [comment] 2021-02-04 18:23
> Choppa already posted this suggestion :)

I dont see it actually, tried to search it

**Comment by Wanhedaa** [comment] 2021-02-04 18:25
Didnt see sorry :D

**Comment by ICCDesi** [comment] 2021-02-04 18:39
Duplicate of #67

**Closed by ICCDesi** 2021-02-04 18:39 UTC
