### ISSUE TITLE
Multiple Realms payment

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#44] opened 2021-01-21 22:04 UTC
Example how to change the booking screen to enable GC taking payments on multiple realms and keeping it separate from the payment the advertiser picked up (so we dont need that excel sheet to keep track how much we need to collect from advertisers for each customer)

![image](https://user-images.githubusercontent.com/77668716/105417531-11b80d80-5c3c-11eb-8843-119cbc0073a2.png)

List of what changes I made:
1. Moved Paid realm and faction from Customer Information to new section "Payment"
2. Moved Price and deposit from Boost to new section "Payment"
3. Made new section called Payment
4. Put 1 & 2 under Payment 
5. Added GC section that advertizers will not see
6. Added line for amount, realm paid and faction for GC
7. Added button to make a new line like nr 6
8. Added GC note area

As I see, this would help a LOT with the current difficulties I have seen from dealing with raids (mostly curve but happens in normal raids too sometimes)

**Comment by iElsha** [comment] 2021-01-22 06:30
duplicate of #6 but, please add your comment there

**Closed by iElsha** 2021-01-22 06:30 UTC
